POST http://localhost:5000/product/createProduct
Content-Type: application/json

{
    "product_name":"Under Armour Men's Charged Assert 9 Running Shoe",
    "price":4600.60,
    "description":"Made in USA or Imported. Rubber sole. Lightweight mesh upper with 3-color digital print delivers complete breathability. Durable leather overlays for stability & that locks in your midfoot",
    "category":" Running Shoes",
    "product_image":"https://m.media-amazon.com/images/I/41l2imvuWJL._AC_UY575_.jpg"


}  
### 
PUT  http://localhost:5000/product/updateProduct
Content-Type: application/json

{
    "product_name":"Merrell MR127 Havoc Vent Casual Shoes",
    "price":17000.60,
    "description":"The men’s Havoc Vent ltr trail shoe from Merrell is perfect for everyday walking and features uppers made from suede leather and mesh with a breathable mesh lining that wicks moisture away from the foot.",
    "category":" Casual",
    "product_image":"https://citywalk.co.ke/wp-content/uploads/2021/10/MR127-510x510.jpg"

}
###
GET http://localhost:5000/product/viewProduct

###
GET http://localhost:5000/product/product/Merrell MR127 Havoc Vent Casual Shoes

###

DELETE  http://localhost:5000/product/product/Merrell MR127 Havoc Vent Casual Shoes

###

POST http://localhost:5000/order/createOrder
Content-Type: application/json

{
    "product_id" :"8",
   "user_id":"1",
   "quantity":"2"
   
}