POST http://localhost:5000/product/createProduct
Content-Type: application/json

{
    "product_name":"Bycicle",
    "price":12000000.00,
    "description":"Mercedes",
    "category":"s-class",
    "product_image":"https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"


}  
### 
PUT  http://localhost:5000/product/updateProduct
Content-Type: application/json

{
    "product_name":"Car",
    "price":15000.00,
    "description":"SuperCar",
    "category":"C-class"

}
###
GET http://localhost:5000/product/viewProduct

###
GET http://localhost:5000/product/product/Bycicle

###

DELETE  http://localhost:5000/product/product/Merrell MR127 Havoc Vent Casual Shoes

###

POST http://localhost:5000/order/createOrder
Content-Type: application/json

{
    "product_id" :"8",
   "user_id":"1",
   "quantity":"2"
   
}