POST http://localhost:5000/register
Content-Type: application/json

{
 
 "user_name":"mjhhbnno", 
"first_name":"kim", 
"last_name":"baohg", 
"email":"mjhhhhjy@gmail.com", 
"password":"ygu5r675q#",  

}

###
POST http://localhost:5000/register/admin
Content-Type: application/json

{
 
"user_name":"odhis", 
"first_name":"Ndambuki", 
"last_name":"Joe", 
"email":"brandyodhiambo@supashop.com", 
"password":"12345", 
"isAdmin":1 

}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"mjhhhhjy@gmail.com",
    "password":"ygu5r675q#"
}
###
PUT  http://localhost:5000/updateProfile
Content-Type: application/json

{
   "userID":1025,  
 "user_name":"odhiambo", 
   "email":"mariogy675vghh@fj.com",
   "password":"ujng567"
   
  
  
}
###
GET http://localhost:5000/users
###
 